# https://couponsb.fra1.cdn.digitaloceanspaces.com/indexer-linux-amd64
name: Run Precompiled Go Binary and Commit Changes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-go-binary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up precompiled binary
        run: |
          # Download the precompiled binary for the appropriate OS (you can use GitHub releases for this)
          curl -L -o indexer-linux-amd64 https://couponsb.fra1.cdn.digitaloceanspaces.com/indexer-linux-amd64
          chmod +x indexer-linux-amd64

      - name: Run Go binary
        run: |
          ./indexer-linux-amd64 --dirname="." # Replace with the actual folder path

      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "Automated index update"
          git push
